spring.application.name=Backend
spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/tesis
spring.datasource.username=postgres
spring.datasource.password=canchia123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
jwt.secret.key=bXlTdXBlclNlY3VyZVNlY3JldEtleUZvckZ1bmRhZUFwcGxpY2F0aW9uVGhhdElzVmVyeUxvbmdBbmRDb21wbGV4

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo@gmail.com
spring.mail.password=tu_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true